WebApplication4/WebApplication4/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class SachController : Controller
    {
        // GET: Sach
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult Index()
        {
            var all_Sach = from aa in data.Saches select aa;
            return View(all_Sach);
        }
        public ActionResult Detail(int id)
        {
            var D_Sach = data.Saches.Where(m => m.masach == id).First();
            return View(D_Sach);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, Sach aa)
        {
            var ten = collection["tensach"];
            if (string.IsNullOrEmpty(ten))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                aa.tensach = ten;
                data.Saches.InsertOnSubmit(aa);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }

        //-------------Edit-------------------
        public ActionResult Edit(int id)
        {
            var E_category = data.Saches.First(m => m.masach == id);
            return View(E_category);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var sach = data.Saches.First(m => m.masach == id);
            var E_tensach = collection["tensach"];
                sach.masach = id;
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
               sach.tensach = E_tensach;
                UpdateModel(sach);
                data.SubmitChanges();
                return RedirectToAction("index");
            }
            return this.Edit(id);
        }
        //-------------Delete-------------------
        public ActionResult Delete(int id)
        {
            var D_Sach = data.Saches.First(m => m.masach == id);
            return View(D_Sach);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_Sach = data.Saches.Where(m => m.masach == id).First();
            data.Saches.DeleteOnSubmit(D_Sach);
            data.SubmitChanges();
            return RedirectToAction("index");
        }
    }
}

WebApplication4/WebApplication4/Views/Sach/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <p>
            Tên thể loại:
            @Html.TextBox("tensach")<font color="red">@ViewData["Error"]</font>
        </p>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication4/WebApplication4/Views/Sach/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>
<fieldset>
    <div class="display-label">Mã loại: @Html.Encode(Model.maloai)</div>
    <div class="display-lable">Tên loại: @Html.Encode(Model.tensach)</div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Delete" />
        @Html.ActionLink("Back to List", "index")
    </p>
}

WebApplication4/WebApplication4/Views/Sach/Detail.cshtml
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>
<fieldset>
    <div class="display-label">Mã loại: @Model.maloai</div>
    <div class="display-label">Tên loại: @Model.tensach</div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        @Html.ActionLink("Delete", "Delete", new { id = Model.masach }) |
        @Html.ActionLink("Edit", "Edit", new { id = Model.masach }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

WebApplication4/WebApplication4/Views/Sach/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="editor-field">
            Tên loại:
            @Html.TextBox("tensach");
            @ViewData["Error"]
        </div>
        <p>
            <input type="submit" value="Save" />

        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication4/WebApplication4/Views/Sach/index.cshtml
@model IEnumerable<WebApplication4.Models.Sach>
@{
    ViewBag.Title = "index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>index</h2>



<h2>Sach</h2>
<table border="1px">
    <tr>
        <th>Mã sách </th>
        <th>Mã loại </th>
        <th>Tên sách </th>
        <th>hình </th>
      
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            
            <td>@item.masach</td>
            <td>@item.maloai</td>
            <td>@item.tensach</td>
            <td>@item.hinh</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.masach }) |
                @Html.ActionLink("Detail", "Detail", new { id = item.masach }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.masach })
            </td>
        </tr>
    }
</table>
@Html.ActionLink("Them", "Create", "Sach")